
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 10 13:12:36 CET 2017
//----------------------------------------------------

package procesadores;

/** CUP generated interface containing symbol constants. */
public interface SintacticoSym {
  /* terminals */
  public static final int eof = 54;
  public static final int dim = 29;
  public static final int t_for = 31;
  public static final int fnx = 48;
  public static final int input = 35;
  public static final int suma = 25;
  public static final int resta = 26;
  public static final int next = 37;
  public static final int cos = 13;
  public static final int no_igual = 10;
  public static final int log = 16;
  public static final int coma = 52;
  public static final int entrada = 4;
  public static final int parentesis_izq = 50;
  public static final int t_return = 43;
  public static final int igual = 9;
  public static final int multiplicacion = 23;
  public static final int sin = 18;
  public static final int t_goto = 33;
  public static final int t_if = 34;
  public static final int let = 36;
  public static final int end = 30;
  public static final int stop = 45;
  public static final int randomize = 40;
  public static final int parentesis_dch = 51;
  public static final int def = 28;
  public static final int read = 41;
  public static final int restore = 42;
  public static final int then = 46;
  public static final int menor = 5;
  public static final int EOF = 0;
  public static final int punto_coma = 53;
  public static final int mayor_igual = 8;
  public static final int error = 1;
  public static final int mayor = 6;
  public static final int abs = 11;
  public static final int sqr = 19;
  public static final int on = 38;
  public static final int step = 44;
  public static final int menor_igual = 7;
  public static final int potencia = 22;
  public static final int rem = 49;
  public static final int variable = 3;
  public static final int tan = 20;
  public static final int atn = 12;
  public static final int gosub = 32;
  public static final int rnd = 21;
  public static final int print = 39;
  public static final int constante = 2;
  public static final int sgn = 17;
  public static final int division = 24;
  public static final int data = 27;
  public static final int exp = 14;
  public static final int to = 47;
  public static final int t_int = 15;
}

